name: Android Build

on:
  push:
    branches: [ "main", "master", "dev" ]
  pull_request:
    branches: [ "main", "master", "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./indogaroapp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.4

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK with Gradle
        run: ./gradlew :app:assembleDevDebug --stacktrace

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jargo-core-apk
          path: ./indogaroapp/app/build/outputs/apk/**/*.apk
