name: JARGO Core Engine Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Compile Android App
    runs-on: ubuntu-latest
    
    # DEKLARASI KRUSIAL: Paksa mesin CI/CD mengeksekusi bash di dalam sub-direktori
    defaults:
      run:
        working-directory: ./indogaroapp

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Generate Gradle Wrapper
      run: gradle wrapper --gradle-version 8.1.0

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build DevDebug APK
      run: ./gradlew assembleDevDebug --stacktrace

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: JARGO-Core-Dev
        path: indogaroapp/app/build/outputs/apk/dev/debug/*.apk
